info = "Baseline with 3 layers and one residual connection"

[wandb]
turn_on = true
entity = "baseline_model"

[dataloader]
# Training DataLoader
train_batch_size = 64
train_num_workers = 4
train_shuffle = true
# Validation DataLoader
test_batch_size = 32
test_num_workers = 4
test_shuffle = false

# Optimizer
[optimizer]
name = "Adam"
    [optimizer.args]
    # Parameters for AdamW optimizer
    lr = 0.001
    # weight_decay = 1e-5

# Learning Rate Scheduler
[lr_scheduler]
name = "None" # "CyclicLR"
    # [lr_scheduler.args]
    # # Parameters for CyclicLR scheduler
    # base_lr=0.001
    # max_lr=0.005
    # step_size_up=50
    # step_size_down=10

[model]
name = "SimpleCNN3Res"

# Training parameters
[training]
epochs = 10
r_ratio_start = 1
r_ratio_decay = 1e-5
r_ratio_min = 0.01

