set BIMSA_LIFE_DIR=.\predictor_life_simple\datasets

python .\predictor_life_simple\life1.py --rule "B1/S"
python .\predictor_life_simple\life1.py --rule "B2/S"
python .\predictor_life_simple\life1.py --rule "B3/S"
python .\predictor_life_simple\life1.py --rule "B4/S"
python .\predictor_life_simple\life1.py --rule "B5/S"
python .\predictor_life_simple\life1.py --rule "B6/S"
python .\predictor_life_simple\life1.py --rule "B7/S"
python .\predictor_life_simple\life1.py --rule "B8/S"
python .\predictor_life_simple\life1.py --rule "B/S1"
python .\predictor_life_simple\life1.py --rule "B/S2"
python .\predictor_life_simple\life1.py --rule "B/S3"
python .\predictor_life_simple\life1.py --rule "B/S4"
python .\predictor_life_simple\life1.py --rule "B/S5"
python .\predictor_life_simple\life1.py --rule "B/S6"
python .\predictor_life_simple\life1.py --rule "B/S7"
python .\predictor_life_simple\life1.py --rule "B/S8"